global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: metrics-sidecar
    metrics_path: /metrics
    static_configs:
      # Try service name (when side-car runs in the same Docker network)
      - targets: ["metrics-sidecar:8001", "host.docker.internal:8001"]
